# Generated by Django 5.1.7 on 2025-03-17 08:06

import ads.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
        migrations.AddField(
            model_name='ad',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='ads_images/', verbose_name='Изображение 1'),
        ),
        migrations.AddField(
            model_name='ad',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='ads_images/', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='ad',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='ads_images/', verbose_name='Изображение 3'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='video_url',
            field=models.URLField(blank=True, null=True, validators=[ads.models.validate_youtube_url], verbose_name='Видео (ссылка на YouTube)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='Автор отклика'),
        ),
    ]
